title: LCR LTDA
logo: /assets/images/logo.png
baseurl: " "
url: https://lcrltda.github.io
repository: "lcrltda/lcrltda.github.io"

##
# Typewritter configuration.
# Feel free to disable if you don't like it.
##
typewriter_effect: true

##
# Collections configuration
##
collections:
  projects:
    output: true

##
# Contact Channels configuration
# Uncomment for enable. Available contact channels are email, github, telegram, stackoverflow, discord, mastodon.
# Please fell free to send a PR if you need a new one.
# DISABLE GITHUB setting it as an empty string: ""
# if false, then no contact channels will be display.
##
contact_channels_section: true
contact_channels:
  # email: "lcrlicitar@gmail.com"
  github: "https://lcrltda.github.io"
  # whatsapp: "https://api.whatsapp.com/send/?phone=85987976492&text&type=phone_number&app_absent=0"
  

##
# Plugins configuration
##
plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed

##
# Archives configuration
##
jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"
