repository: "lcrltda/lcrltda.github.io"
title: LCR LTDA
logo: /assets/images/logo.png
baseurl: ""
url: https://lcrltda.github.io

google_fonts: "Cormorant+Garamond:wght@500;600|IBM+Plex+Sans:wght@400;500"

##
# Typewritter configuration.
# Feel free to disable if you don't like it.
##
typewriter_effect: true

##
# Collections configuration
##
collections:
  projects:
    output: true

##
# Contact Channels configuration
# Uncomment for enable. Available contact channels are email, github, telegram, stackoverflow, discord, mastodon.
# Please fell free to send a PR if you need a new one.
# DISABLE GITHUB setting it as an empty string: ""
# if false, then no contact channels will be display.
##
contact_channels_section: true
contact_channels:
  email: "lcrlicitar@gmail.com"  
  github: "lcrltda.github.io"  
  telegram: "https://wa.me/5585987976492"  # Desativa Telegram
  stackoverflow: ""  # Desativa StackOverflow
  discord: ""  # Desativa Discord
  mastodon: ""  # Desativa Mastodon

##
# Plugins configuration
##
plugins:
  - jekyll-github-metadata
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-feed

##
# Archives configuration
##
jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"
